In [27]:
import numpy as np

#Create array
A= np.array([1,2,3])
print(A)
#Print 1 element
element=A[1]
print(element)

# Create 2nd dim array
matrix =np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix : ")
print(matrix)
#print element
element=matrix[1,2]
print(element)

#Create Array
#Array full of 0
a=np.zeros(5)
print(a)

#Array full of 1
a=np.ones(5)
print(a)

#Array from 0 - 100
a=np.arange(100)
print(a)

#Array include elements with equal linspace
a = np.linspace(0,10,num=5)
print(a)

#Determine data type
a = np.ones(5,dtype=np.int64)
a

[1 2 3]
2
Matrix : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[ 0.   2.5  5.   7.5 10. ]


array([1, 1, 1, 1, 1], dtype=int64)

In [35]:
#Create 1 way array
arr= np.array([5,2,1,9,6])
print(arr)

#Arrange
arr=np.sort(arr)
print(arr)

#Opposite Arrange
arr = np.sort(arr)[::-1]
print(arr)

#Add elements to array
arr = np.append(arr,100)
print(arr)

# Delete a specific order in Array
arr = np.delete(arr,3)
print(arr)

[5 2 1 9 6]
[1 2 5 6 9]
[9 6 5 2 1]
[  9   6   5   2   1 100]
[  9   6   5   1 100]


In [49]:
#Create 2nd dim array
arr_2nd =np.array([
    [3,11,2],
    [3,1,6],
    [7,2,9]])

#Increasing
#Row arrange
Row_arr=np.sort(arr_2nd,axis=1) 
print(Row_arr)
#column arrange
Com_arr=np.sort(arr_2nd,axis=0)
print(Com_arr)

print('==================')
#Decreasing
#Row arrange
Row_arr=np.sort(-arr_2nd,axis=1) 
print(Row_arr)
#column arrange
Com_arr=np.sort(-arr_2nd,axis=0)
print(Com_arr)

[[ 2  3 11]
 [ 1  3  6]
 [ 2  7  9]]
[[ 3  1  2]
 [ 3  2  6]
 [ 7 11  9]]
[[-11  -3  -2]
 [ -6  -3  -1]
 [ -9  -7  -2]]
[[ -7 -11  -9]
 [ -3  -2  -6]
 [ -3  -1  -2]]


In [53]:
#Create 2nd dim array
arr_2nd =np.array([
    [3,11,2],
    [3,1,6]])
dim=arr_2nd.ndim #Quantity of array's dim
size=arr_2nd.size #Size of array(element counts)
shape=arr_2nd.shape # Shape of the array/matrix
print("Dimesions : ",dim)
print("Size : ",size)
print("Shape : ",shape)

Dimesions :  2
Size :  6
Shape :  (2, 3)
[5. 2. 1. 9. 6.]


In [61]:
#Change datatype
arr= np.array([5,2,1,9,6])
arr_float=arr.astype(float) 
print(arr_float)
print('====================')

#Change the shape of matrix/array
arr= np.array([5,2,1,9,6,8])
rs_arr=arr.reshape(2,3)
print(rs_arr)
rs_arr=arr.reshape(3,2)
print(rs_arr)
rs_arr=rs_arr.flatten() # Change to 1 dim array
print(rs_arr)

[5. 2. 1. 9. 6.]
[[5 2 1]
 [9 6 8]]
[[5 2]
 [1 9]
 [6 8]]
[5 2 1 9 6 8]


In [81]:
#Slice array
arr = np.array([5,2,1,9,6,8])
sub_arr=arr[1:4] #Cut order 1-4 in array
print(sub_arr)
print('====================')
sub_arr=arr[:-1] # Cut the last element of array
print(sub_arr)
print('====================')
sub_arr=arr[-2:] # Take the last 2 elements of array
print(sub_arr)

[2 1 9]
[5 2 1 9 6]
[6 8]


In [87]:
#Create 2nd dim array
arr_2nd =np.array([
    [3,11,2],
    [3,1,6]])
trans_arr=arr_2nd.T #can use array.T or numpy.transpose()
print(trans_arr)
print('====================')

#Link arrays
arr1 = np.array([5,2,1])
arr2 = np.array([9,6,8])
arr=np.concatenate((arr1,arr2))
print(arr)

[[ 3  3]
 [11  1]
 [ 2  6]]
[5 2 1 9 6 8]


In [101]:
#Sum math
#Use numpy.sum() to sum elements in array
arr = np.array([5,2,1,9,6,8])
total = np.sum(arr)
print('Total: ',total)
print('====================')

#Avarage math
#Use numpy.mean() to calc avarage value of elements in array
avr=np.mean(arr)
print('Avarage : ',avr)
print('====================')

#Max and min method
#Use numpy.max() and numpy.min() to 
#find out max and min value of elements of the array/matrix
max=np.max(arr)
min=np.min(arr)
print('Max : ',max)
print('Min : ',min)
print('====================')

#Deviation calc
#Use numpy.std() to calc std deviation of array/matrix,calc degree of data dispersion
std = np.std(arr)
print('Std deviation : ',std)
print('====================')

#Variance calc
#Use numpy.var() to calc Variance of array,calc the degree of variability of the data
var = np.var(arr)
print('Variance : ',var)
print('====================')

#Dot product calc
#Use numpy.dot() to calc convolutional sum of two arrays
arr1 = np.array([5,2,1])
arr2 = np.array([9,6,8])
dot = np.dot(arr1,arr2)
print('Dot product of arr1 and arr2 : ',dot)

Total:  31
Avarage :  5.166666666666667
Max :  9
Min :  1
Std deviation :  2.9107081994288304
Variance :  8.472222222222223
Dot product of arr1 and arr2 :  65
